---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/addon-ci.yaml@main
    with:
      slug: "grott"

  check_image:
    runs-on: ubuntu-latest
    needs: workflows
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - name: 🚀 Run add-on information action
        id: information
        uses: frenck/action-addon-information@v1.4.2
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: 🏗 Set up build cache
        id: cache
        uses: actions/cache@v4.0.1
        with:
          path: /tmp/.docker-cache
          key: docker-amd64-${{ github.sha }}
          restore-keys: |
            docker-docker-amd64
      - name: 🏗 Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: 🏗 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0
      - name: 🏗  Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: ⤵️ Download base image
        run: docker pull ${{ steps.information.outputs.build }}"

      # install goss and dgoss
      - name: Install goss
        run: |
          curl -fsSL https://goss.rocks/install | sh
          sudo mv ./goss /usr/local/bin/goss
          sudo chmod +rx /usr/local/bin/goss
          curl -fsSL https://dgoss.rocks/install | sh
          sudo mv ./dgoss /usr/local/bin/dgoss
          sudo chmod +rx /usr/local/bin/dgossneeds
      # run goss tests
      - name: Run goss tests
        run: |
          dgoss run "ghcr.io/${{ github.repository_owner }}/${{ steps.information.outputs.slug }}/amd64:edge"
