---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/addon-ci.yaml@main
    with:
      slug: "grott"

  check_image:
    runs-on: ubuntu-latest
    needs: workflows
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - name: 🚀 Run add-on information action
        id: information
        uses: frenck/action-addon-information@v1.4.2
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: 🏗 Set up build cache
        id: cache
        uses: actions/cache@v4.0.1
        with:
          path: /tmp/.docker-cache
          key: docker-${{ github.ref }}-amd65-${{ github.sha }}
          restore-keys: |
            docker-${{ github.ref }}-amd64
      - name: 🏗 Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: 🏗 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0
      - name: 🏗  Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: ⤵️ Download base image
        # pull from cache
        run: |
          ls -l /tmp/.docker-cache
          docker pull "ghcr.io/${{ github.repository_owner }}/${{ steps.information.outputs.slug }}/amd64:edge"

      # install goss and dgoss
      - name: Install goss
        run: |
          VERSION=v0.4.4
          curl -L "https://github.com/goss-org/goss/releases/download/${VERSION}/goss-linux-amd64" -o /usr/local/bin/goss
          chmod +rx /usr/local/bin/goss

          VERSION=v0.4.4
          curl -L "https://github.com/goss-org/goss/releases/download/${VERSION}/dgoss" -o /usr/local/bin/dgoss
          chmod +rx /usr/local/bin/dgoss
      # run goss tests
      - name: Run goss tests
        run: |
          dgoss run "ghcr.io/${{ github.repository_owner }}/${{ steps.information.outputs.slug }}/amd64:edge"
